title: "FLY Documentation"
remote_theme: pmarsceill/just-the-docs
color_scheme: "fly"
search_enabled: false

# Footer last edited timestamp
footer_content: Visit our GitHub <a href="https://github.com/fly-language">repository</a>.

# Aux links for the upper right navigation
aux_links:
  "FLY on GitHub":
    - "https://github.com/fly-language"
